language: python
group: travis_latest
dist: xenial
sudo: true

env:
    global:
        - github_master="https://github.com/${TRAVIS_REPO_SLUG}/archive/master.zip"
        - pip_command="pip"
        - python_command="python"

addons:
    apt:
        packages:
            - xvfb      # install xvfb virtual framebuffer - not really necessary because already installed on travis
            - winbind   # needed for wine

services:   # start services
  - xvfb    # can be used for wine - not needed if You test console applications, but we start it anyway


matrix:
    include:
    - os: windows
      language: sh
      name: "Windows Python 2.7"

      # oddly a secure password under env: global: causes that choco fails
      # so we need to put the option : filter_secrets: false
      # this can be a security issue, check that You dont leak secrets here !
      filter_secrets: false

      before_install:
          - choco install python2
          - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"

    - os: windows
      language: sh
      name: "Windows Python 3.7"

      # oddly a secure password under env: global: causes that choco fails
      # so we need to put the option : filter_secrets: false
      # this can be a security issue, check that You dont leak secrets here !
      filter_secrets: false

      before_install:
        - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"

    - os: linux
      language: sh
      name: "WINE stable 32 Bit Python 2.7.16, Windows XP"
      env:
          - WINEARCH="win32"
          - WINEPREFIX="${HOME}/wine/wine32"
          - WINEPATH="c:/PortableGit32/cmd;c:/Python27-32;c:/Python27-32/Scripts"
          - CMDPREFIX="wine"
          - wine_windows_version="winxp"
          - wine_version="stable"
          - wine_python_version="python2"

    - os: linux
      language: sh
      name: "WINE stable 64 Bit Python 2.7.16, Windows XP"
      env:
          - WINEPREFIX="${HOME}/wine/wine64"
          - WINEPATH="c:/PortableGit64/cmd;c:/Python27-64;c:/Python27-64/Scripts"
          - CMDPREFIX="wine"
          - wine_windows_version="winxp"
          - wine_version="stable"
          - wine_python_version="python2"

    - os: linux
      language: sh
      name: "WINE stable 32 Bit Python 3.7.3, Windows XP"
      env:
          - WINEARCH="win32"
          - WINEPREFIX="${HOME}/wine/wine32"
          - WINEPATH="c:/PortableGit32/cmd;c:/Python37-32;c:/Python37-32/Scripts"
          - CMDPREFIX="wine"
          - wine_windows_version="winxp"
          - wine_version="stable"
          - wine_python_version="python3"

    - os: linux
      language: sh
      name: "WINE stable 64 Bit Python 3.7.3, Windows XP"
      env:
          - WINEPREFIX="${HOME}/wine/wine64"
          - WINEPATH="c:/PortableGit64/cmd;c:/Python37-64;c:/Python37-64/Scripts"
          - CMDPREFIX="wine"
          - wine_windows_version="winxp"
          - wine_version="stable"
          - wine_python_version="python3"

    - os: linux
      language: sh
      name: "WINE stable 32 Bit Python 2.7.16, Windows 10"
      env:
          - WINEARCH="win32"
          - WINEPREFIX="${HOME}/wine/wine32"
          - WINEPATH="c:/PortableGit32/cmd;c:/Python27-32;c:/Python27-32/Scripts"
          - CMDPREFIX="wine"
          - wine_windows_version="win10"
          - wine_version="stable"
          - wine_python_version="python2"

    - os: linux
      language: sh
      name: "WINE stable 64 Bit Python 2.7.16, Windows 10"
      env:
          - WINEPREFIX="${HOME}/wine/wine64"
          - WINEPATH="c:/PortableGit64/cmd;c:/Python27-64;c:/Python27-64/Scripts"
          - CMDPREFIX="wine"
          - wine_windows_version="win10"
          - wine_version="stable"
          - wine_python_version="python2"

    - os: linux
      language: sh
      name: "WINE stable 32 Bit Python 3.7.3, Windows 10"
      env:
          - WINEARCH="win32"
          - WINEPREFIX="${HOME}/wine/wine32"
          - WINEPATH="c:/PortableGit32/cmd;c:/Python37-32;c:/Python37-32/Scripts"
          - CMDPREFIX="wine"
          - wine_windows_version="win10"
          - wine_version="stable"
          - wine_python_version="python3"

    - os: linux
      language: sh
      name: "WINE stable 64 Bit Python 3.7.3, Windows 10"
      env:
          - WINEPREFIX="${HOME}/wine/wine64"
          - WINEPATH="c:/PortableGit64/cmd;c:/Python37-64;c:/Python37-64/Scripts"
          - CMDPREFIX="wine"
          - wine_windows_version="win10"
          - wine_version="stable"
          - wine_python_version="python3"
      # we can do that also with env - but we dont want to show it on the travis build overview
      before_install:
        - export deploy_on_pypi="True"

    - os: linux
      language: sh
      name: "WINE devel 32 Bit Python 2.7.16, Windows XP"
      env:
          - WINEARCH="win32"
          - WINEPREFIX="${HOME}/wine/wine32"
          - WINEPATH="c:/PortableGit32/cmd;c:/Python27-32;c:/Python27-32/Scripts"
          - CMDPREFIX="wine"
          - wine_windows_version="winxp"
          - wine_version="devel"
          - wine_python_version="python2"

    - os: linux
      language: sh
      name: "WINE devel 64 Bit Python 2.7.16, Windows XP"
      env:
          - WINEPREFIX="${HOME}/wine/wine64"
          - WINEPATH="c:/PortableGit64/cmd;c:/Python27-64;c:/Python27-64/Scripts"
          - CMDPREFIX="wine"
          - wine_windows_version="winxp"
          - wine_version="devel"
          - wine_python_version="python2"

    - os: linux
      language: sh
      name: "WINE devel 32 Bit Python 3.7.3, Windows XP"
      env:
          - WINEARCH="win32"
          - WINEPREFIX="${HOME}/wine/wine32"
          - WINEPATH="c:/PortableGit32/cmd;c:/Python37-32;c:/Python37-32/Scripts"
          - CMDPREFIX="wine"
          - wine_windows_version="winxp"
          - wine_version="devel"
          - wine_python_version="python3"

    - os: linux
      language: sh
      name: "WINE devel 64 Bit Python 3.7.3, Windows XP"
      env:
          - WINEPREFIX="${HOME}/wine/wine64"
          - WINEPATH="c:/PortableGit64/cmd;c:/Python37-64;c:/Python37-64/Scripts"
          - CMDPREFIX="wine"
          - wine_windows_version="winxp"
          - wine_version="devel"
          - wine_python_version="python3"

    - os: linux
      language: sh
      name: "WINE devel 32 Bit Python 2.7.16, Windows 10"
      env:
          - WINEARCH="win32"
          - WINEPREFIX="${HOME}/wine/wine32"
          - WINEPATH="c:/PortableGit32/cmd;c:/Python27-32;c:/Python27-32/Scripts"
          - CMDPREFIX="wine"
          - wine_windows_version="win10"
          - wine_version="devel"
          - wine_python_version="python2"

    - os: linux
      language: sh
      name: "WINE devel 64 Bit Python 2.7.16, Windows 10"
      env:
          - WINEPREFIX="${HOME}/wine/wine64"
          - WINEPATH="c:/PortableGit64/cmd;c:/Python27-64;c:/Python27-64/Scripts"
          - CMDPREFIX="wine"
          - wine_windows_version="win10"
          - wine_version="devel"
          - wine_python_version="python2"

    - os: linux
      language: sh
      name: "WINE devel 32 Bit Python 3.7.3, Windows 10"
      env:
          - WINEARCH="win32"
          - WINEPREFIX="${HOME}/wine/wine32"
          - WINEPATH="c:/PortableGit32/cmd;c:/Python37-32;c:/Python37-32/Scripts"
          - CMDPREFIX="wine"
          - wine_windows_version="win10"
          - wine_version="devel"
          - wine_python_version="python3"

    - os: linux
      language: sh
      name: "WINE devel 64 Bit Python 3.7.3, Windows 10"
      env:
          - WINEPREFIX="${HOME}/wine/wine64"
          - WINEPATH="c:/PortableGit64/cmd;c:/Python37-64;c:/Python37-64/Scripts"
          - CMDPREFIX="wine"
          - wine_windows_version="win10"
          - wine_version="devel"
          - wine_python_version="python3"

    - os: linux
      language: sh
      name: "WINE staging 32 Bit Python 2.7.16, Windows XP"
      env:
          - WINEARCH="win32"
          - WINEPREFIX="${HOME}/wine/wine32"
          - WINEPATH="c:/PortableGit32/cmd;c:/Python27-32;c:/Python27-32/Scripts"
          - CMDPREFIX="wine"
          - wine_windows_version="winxp"
          - wine_version="staging"
          - wine_python_version="python2"

    - os: linux
      language: sh
      name: "WINE staging 64 Bit Python 2.7.16, Windows XP"
      env:
          - WINEPREFIX="${HOME}/wine/wine64"
          - WINEPATH="c:/PortableGit64/cmd;c:/Python27-64;c:/Python27-64/Scripts"
          - CMDPREFIX="wine"
          - wine_windows_version="winxp"
          - wine_version="staging"
          - wine_python_version="python2"

    - os: linux
      language: sh
      name: "WINE staging 32 Bit Python 3.7.3, Windows XP"
      env:
          - WINEARCH="win32"
          - WINEPREFIX="${HOME}/wine/wine32"
          - WINEPATH="c:/PortableGit32/cmd;c:/Python37-32;c:/Python37-32/Scripts"
          - CMDPREFIX="wine"
          - wine_windows_version="winxp"
          - wine_version="staging"
          - wine_python_version="python3"

    - os: linux
      language: sh
      name: "WINE staging 64 Bit Python 3.7.3, Windows XP"
      env:
          - WINEPREFIX="${HOME}/wine/wine64"
          - WINEPATH="c:/PortableGit64/cmd;c:/Python37-64;c:/Python37-64/Scripts"
          - CMDPREFIX="wine"
          - wine_windows_version="winxp"
          - wine_version="staging"
          - wine_python_version="python3"

    - os: linux
      language: sh
      name: "WINE staging 32 Bit Python 2.7.16, Windows 10"
      env:
          - WINEARCH="win32"
          - WINEPREFIX="${HOME}/wine/wine32"
          - WINEPATH="c:/PortableGit32/cmd;c:/Python27-32;c:/Python27-32/Scripts"
          - CMDPREFIX="wine"
          - wine_windows_version="win10"
          - wine_version="staging"
          - wine_python_version="python2"

    - os: linux
      language: sh
      name: "WINE staging 64 Bit Python 2.7.16, Windows 10"
      env:
          - WINEPREFIX="${HOME}/wine/wine64"
          - WINEPATH="c:/PortableGit64/cmd;c:/Python27-64;c:/Python27-64/Scripts"
          - CMDPREFIX="wine"
          - wine_windows_version="win10"
          - wine_version="staging"
          - wine_python_version="python2"

    - os: linux
      language: sh
      name: "WINE staging 32 Bit Python 3.7.3, Windows 10"
      env:
          - WINEARCH="win32"
          - WINEPREFIX="${HOME}/wine/wine32"
          - WINEPATH="c:/PortableGit32/cmd;c:/Python37-32;c:/Python37-32/Scripts"
          - CMDPREFIX="wine"
          - wine_windows_version="win10"
          - wine_version="staging"
          - wine_python_version="python3"

    - os: linux
      language: sh
      name: "WINE staging 64 Bit Python 3.7.3, Windows 10"
      env:
          - WINEPREFIX="${HOME}/wine/wine64"
          - WINEPATH="c:/PortableGit64/cmd;c:/Python37-64;c:/Python37-64/Scripts"
          - CMDPREFIX="wine"
          - wine_windows_version="win10"
          - wine_version="staging"
          - wine_python_version="python3"


install:
    - if [[ ${CMDPREFIX} == "wine" ]]; then chmod 755 ./*.sh ; fi
    - if [[ ${CMDPREFIX} == "wine" ]]; then ./install_wine.sh ; fi
    - if [[ ${CMDPREFIX} == "wine" ]]; then ./install_wine_machine.sh ; fi
    - if [[ ${wine_python_version} == "python2" ]]; then ./install_wine_python2_preinstalled.sh ; fi
    - if [[ ${wine_python_version} == "python3" ]]; then ./install_wine_python3_preinstalled.sh ; fi
    - if [[ ${CMDPREFIX} == "wine" ]]; then ./install_wine_git_portable.sh ; fi

    - ${CMDPREFIX} ${python_command} -m pip install --upgrade pip
    - if [[ $TRAVIS_PYTHON_VERSION == pypy3.5-6.0 ]]; then ${CMDPREFIX} ${pip_command} install "pytest-cov==2.6.0"; fi
    - ${CMDPREFIX} ${pip_command} install codecov pytest pytest-pep8 pytest-cov dill
    - ${CMDPREFIX} ${pip_command} install -e .

script:
    - ${CMDPREFIX} ${pip_command} install ${github_master} --install-option test # test setup.py test option
    - ${CMDPREFIX} ${python_command} -m pytest --pep8 --cov

after_success:
    - ${CMDPREFIX} coverage report
    - ${CMDPREFIX} codecov

    # This works for sure - but might expose the secure password within the matrix,
    # because windows builds need filter_secrets: false at the Moment (2019-04-12)
    # - if [[ ${deploy_on_pypi} == "True" ]] && [[ -n ${TRAVIS_TAG} ]]; then ${CMDPREFIX} ${pip_command} install -U twine ; fi
    # - if [[ ${deploy_on_pypi} == "True" ]] && [[ -n ${TRAVIS_TAG} ]]; then ${CMDPREFIX} ${pip_command} install wheel ; fi
    # - if [[ ${deploy_on_pypi} == "True" ]] && [[ -n ${TRAVIS_TAG} ]]; then ${CMDPREFIX} ${python_command} setup.py sdist bdist_wheel ; fi
    # - if [[ ${deploy_on_pypi} == "True" ]] && [[ -n ${TRAVIS_TAG} ]]; then ${CMDPREFIX} twine upload --repository-url https://upload.pypi.org/legacy/ -u bitranox -p ${pypi_password} dist/* ; fi


# the password needs to be encrypted pointing to ${deploy.password}
# make a backup before adding secrets by travis gem, all comments in the yml files get lost !
# password needs to be created from the project directory for every repository with ruby gem travis:   travis encrypt "*******" --add deploy.password --org
# option --org for travis.org, --com for travis.com

deploy:
  provider: pypi
  user: bitranox
  password:
    secure: BxMY49GdbccfXA2k1efRi+vyzgG65hXx5u75BRvf2X4MfIYE0HAoRt6b+p5NIcBe7RrGShgX0r2fJyQOaGshyfd+Us2Gf5PFgAJYqNU7gHtZIM4GFek1BJH+fRg4SYPVI6IjsDI+sLcPXK7hh1x0wm+Y4+Npa3RqvvNaLrMnNTSa76y5g9guYVCJaxOqgQwdTbzyjGOTKKBtUMVn3/NkjiTG0c4+Rf91uAjqLi/G0vBXX0BJ5LltVpTpi4KvPKxMS/IAtKRM2yXZhe2TTBBPwZ3jmiUIOTnDvQltznL9wPDAYBVm4inkX0WEj4Ly48H2HFboAnqXlbZH4EE9btsuTQGWJI0HOK16ZI36L4UslHCxZm9/IkB4XDUTQw6VlfZ5a0He/6HAKnqu/YFG71vSV8a1pwo/LxVt0Swaqh5GGsYOM3Yh9ZDdce1kH4JkB2/r14oe3BJuRU2r9fee48YltI8iTrixKIelrBKph+lekxnqVmeyD3w60tFXPAcjhfo1BcOxv26kmv6UvqIiRHlBIG73+XnIC3kKmm9KW/4uKAU+5Q3DuGDMAPwTcAy/oCbkgDAioVFn7qfEtYWJsfdvaGU7kwloDCyT7W71cYO4h5dJETjSQHx02kZ8Ll/llMN9YwYFZ9iL30nKPNnE0T8TL5r2yOoqGRBjRYm9xhtq/2c=
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    # python: 3.6
    # we need this, because on projects with windows builds only, we can not build on windows, because of
    # the filter_secure issue. So we build on WINE, but need somehow to address the matrix include on which to build
    condition: ${deploy_on_pypi} = "True"
